apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gradio
  template:
    metadata:
      labels:
        app: gradio
    spec:
      containers:
      - name: gradio
        image: ${IMAGE_NAME}
        env:
          - name: MODEL_URL
            value: "http://sentiment-classification-service"
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: llm-cluster
                key: OPENAI_API_KEY
          - name: OPENAI_ORG_ID
            valueFrom:
              secretKeyRef:
                name: llm-cluster
                key: OPENAI_ORG_ID
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 7860
---
apiVersion: v1
kind: Service
metadata:
  name: gradio-service
spec:
  type: LoadBalancer
  selector:
    app: gradio
  ports:
  - port: 80
    targetPort: 7860