apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-classification
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentiment-classification
  template:
    metadata:
      labels:
        app: sentiment-classification
    spec:
      containers:
      - name: sentiment-classification
        image: quay.io/codait/max-text-sentiment-classifier:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-classification-service
spec:
  selector:
    app: sentiment-classification
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000